version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - locals-service
      - order-service
      - notification-service

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"

  locals-service:
    build: ./locals-service
    ports:
      - "3002:3002"

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3004"
